"""MEGB-03D: independent validation of the HumanEval/6, /55, and /63
supplementary-input oracle (MEGB-03A.1/MEGB-03C).

These three tasks' supplementary cases (contract-derived, generated by
``src.reference.augmentation``, never from a model or candidate) have no
upstream EvalPlus counterpart — there is nothing to compare against via
``src.reference.parity``. Instead, this module cross-checks MEGB-03C's
oracle values two independent ways:

1. **Independent implementation** — a second reference solution for each
   task, written using a genuinely different algorithmic approach than the
   pinned canonical solution (stack-based vs. counter-based for
   ``parse_nested_parens``; memoized recursion vs. iteration for ``fib``/
   ``fibfib``), compared against the same canonical-solution-derived
   expected value MEGB-03C's oracle uses.
2. **Metamorphic/boundary checks** — task-appropriate invariants that must
   hold regardless of which implementation computed the value (the
   recurrence relation for ``fib``/``fibfib``; concatenation-independence
   of per-group nesting depth for ``parse_nested_parens``).

This is explicitly *supplementary-oracle validation*, not upstream parity
(there is no "upstream" here) — reported as its own section, never folded
into the parity corpus's classification-agreement acceptance evidence.
"""

import copy
from dataclasses import dataclass
from typing import Any, Callable, Mapping

from evalplus.eval.utils import time_limit

from src.dataset import PrivilegedTaskView
from src.reference.augmentation import PROVENANCE_SUPPLEMENTARY, build_canonical_callable

SUPPLEMENTARY_TASK_IDS = ("HumanEval/6", "HumanEval/55", "HumanEval/63")
_TRUSTED_TIME_LIMIT_SEC = 5.0


def independent_parse_nested_parens(paren_string: str) -> list[int]:
    """Stack-based reimplementation of HumanEval/6 (the canonical solution
    tracks depth with a running increment/decrement counter instead)."""
    depths = []
    for group in paren_string.split(" "):
        if group == "":
            continue
        stack: list[str] = []
        max_depth = 0
        for ch in group:
            if ch == "(":
                stack.append(ch)
                max_depth = max(max_depth, len(stack))
            elif ch == ")":
                stack.pop()
        depths.append(max_depth)
    return depths


def independent_fib(n: int) -> int:
    """Memoized-recursion reimplementation of HumanEval/55 (the canonical
    solution is iterative)."""
    memo: dict[int, int] = {0: 0, 1: 1, 2: 1}

    def helper(k: int) -> int:
        if k not in memo:
            memo[k] = helper(k - 1) + helper(k - 2)
        return memo[k]

    return helper(n)


def independent_fibfib(n: int) -> int:
    """Memoized-recursion reimplementation of HumanEval/63 (the canonical
    solution is iterative)."""
    memo: dict[int, int] = {0: 0, 1: 0, 2: 1}

    def helper(k: int) -> int:
        if k not in memo:
            memo[k] = helper(k - 1) + helper(k - 2) + helper(k - 3)
        return memo[k]

    return helper(n)


INDEPENDENT_IMPLEMENTATIONS: Mapping[str, Callable[..., Any]] = {
    "HumanEval/6": independent_parse_nested_parens,
    "HumanEval/55": independent_fib,
    "HumanEval/63": independent_fibfib,
}


def _metamorphic_checks_parse_nested_parens(
    canonical_fn: Callable[..., Any], args_by_case: Mapping[str, tuple[Any, ...]]
) -> tuple[int, int]:
    """Concatenating two space-separated groups must yield the concatenation
    of their individually computed depths — groups are independent."""
    strings = [args[0] for args in args_by_case.values() if args[0]]
    passed = 0
    total = 0
    for i in range(min(len(strings), 20)):
        a = strings[i]
        b = strings[(i + 7) % len(strings)]
        total += 1
        combined = canonical_fn(f"{a} {b}")
        separate = canonical_fn(a) + canonical_fn(b)
        if combined == separate:
            passed += 1
    return passed, total


def _metamorphic_checks_recurrence(
    canonical_fn: Callable[..., Any], args_by_case: Mapping[str, tuple[Any, ...]], order: int
) -> tuple[int, int]:
    """fib/fibfib's own defining recurrence must hold for every case whose
    ``order`` preceding values are also independently computable."""
    passed = 0
    total = 0
    for args in args_by_case.values():
        n = args[0]
        if n < order:
            continue
        total += 1
        lhs = canonical_fn(n)
        rhs = sum(canonical_fn(n - i) for i in range(1, order + 1))
        if lhs == rhs:
            passed += 1
    return passed, total


@dataclass(frozen=True)
class SupplementaryTaskValidation:
    """One task's complete supplementary-oracle validation outcome."""

    task_id: str
    total_supplementary_cases: int
    independent_match_count: int
    metamorphic_checks_passed: int
    metamorphic_checks_total: int

    @property
    def all_valid(self) -> bool:
        """True iff every supplementary case matched independently and every
        metamorphic check passed, over a nonempty case set."""
        return (
            self.independent_match_count == self.total_supplementary_cases
            and self.metamorphic_checks_passed == self.metamorphic_checks_total
            and self.total_supplementary_cases > 0
        )


def _supplementary_case_args(
    args_by_case: Mapping[str, tuple[Any, ...]], provenance_by_case: Mapping[str, str]
) -> dict[str, tuple[Any, ...]]:
    return {
        cid: args
        for cid, args in args_by_case.items()
        if provenance_by_case.get(cid) == PROVENANCE_SUPPLEMENTARY
    }


def validate_supplementary_task(
    task_id: str,
    privileged: PrivilegedTaskView,
    prompt: str,
    args_by_case: Mapping[str, tuple[Any, ...]],
    provenance_by_case: Mapping[str, str],
) -> SupplementaryTaskValidation:
    """Validate one task's supplementary-input oracle independently of its canonical solution."""
    canonical_fn = build_canonical_callable(
        prompt, privileged.canonical_solution, privileged.entry_point
    )
    independent_fn = INDEPENDENT_IMPLEMENTATIONS[task_id]
    supplementary_args = _supplementary_case_args(args_by_case, provenance_by_case)

    independent_match_count = 0
    for args in supplementary_args.values():
        with time_limit(_TRUSTED_TIME_LIMIT_SEC):
            expected = canonical_fn(*copy.deepcopy(args))
            actual = independent_fn(*copy.deepcopy(args))
        if actual == expected:
            independent_match_count += 1

    if task_id == "HumanEval/6":
        metamorphic_passed, metamorphic_total = _metamorphic_checks_parse_nested_parens(
            canonical_fn, supplementary_args
        )
    elif task_id == "HumanEval/55":
        metamorphic_passed, metamorphic_total = _metamorphic_checks_recurrence(
            canonical_fn, supplementary_args, order=2
        )
    elif task_id == "HumanEval/63":
        metamorphic_passed, metamorphic_total = _metamorphic_checks_recurrence(
            canonical_fn, supplementary_args, order=3
        )
    else:
        raise ValueError(f"no supplementary validation defined for {task_id!r}")

    return SupplementaryTaskValidation(
        task_id=task_id,
        total_supplementary_cases=len(supplementary_args),
        independent_match_count=independent_match_count,
        metamorphic_checks_passed=metamorphic_passed,
        metamorphic_checks_total=metamorphic_total,
    )
